name: Run Spider

on:
  schedule:
    - cron: '35 12 * * *'  # Run the job every day at 11:15 AM UTC => 5:00 Nepal Time

jobs:
  run_spider:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '20'
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          node-version: '20'
          python-version: 3.9


      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run spider
        run: scrapy crawl market

      - name: Commit and Push Files
        run: |
            git config user.email "mail@pranilshrestha.com.np"
            git config user.name "fuunshi"
            git add .
            git commit -am "Share data has been successfully scrapped"
            git push origin main
